Create Product Search.jsp
HTTP Status 500 - An exception occurred processing JSP page /admin/ProductSearch.jsp at line 21
message An exception occurred processing JSP page /admin/ProductSearch.jsp at line 21
description The server encountered an internal error that prevented it from fulfilling this request.
exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /admin/ProductSearch.jsp at line 21

18:        String keyword = request.getParameter("keyword");
19:        double lowNormalprice = Double.parseDouble(request.getParameter("lowNormalprice")); 
20:        double highNormalprice = Double.parseDouble(request.getParameter("highNormalprice")); 
21:        double lowMemberprice = Double.parseDouble(request.getParameter("lowMemberprice")); 
22:        double highMemberprice = Double.parseDouble(request.getParameter("highMemberprice"));
23:        int categoryid = Integer.parseInt(request.getParameter("categoryid"));
24:        int[] idArray;


Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:580)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

java.lang.NumberFormatException: empty String
	sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	java.lang.Double.parseDouble(Double.java:538)
	org.apache.jsp.admin.ProductSearch_jsp._jspService(ProductSearch_jsp.java:105)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.78 logs.